### ISSUE TITLE
wazuh indexer - could not find java in JAVA_HOME

### ISSUE THREAD

**Issue by t0mal0** [kalingth/wazuh-docker-builder#1]
Hi. Pod show error on start .

kubectl logs wazuh-indexer-0 -n wazuh -f                                                                   
Defaulted container "wazuh-indexer" out of: wazuh-indexer, volume-mount-hack (init), increase-the-vm-max-map-count (init)
could not find java in JAVA_HOME at /usr/share/wazuh-indexer/jdk/bin/java

Probably error is here:
https://github.com/kalingth/wazuh-docker-builder/blob/51de5ef5bba873151312c7cd7cd6e4e168fb44d8/wazuh-indexer/config/config.sh#L154

Now, after downloading java from oracle we have jdk-22.0.2.

**Comment by kalingth** [comment]
Hello. Thank you for your feedback.

Indeed, there is a bug when unpacking the JDK and moving the folder. In the first build, this error didn’t occur because the downloaded JDK was version 22.0.1. However, while I was releasing the hotfix for the s6 pro arm build, the JDK was updated to version 22.0.2, as you rightly pointed out.

I will submit a hotfix pull request for all the built versions to ensure a more robust build, and that all images will correctly refer to the appropriate JDK version.

Let me know if you need any further adjustments!
